/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SupervisorRouteImport } from './routes/supervisor'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as CctvRouteImport } from './routes/cctv'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesIdRouteImport } from './routes/cases_.$id'
import { Route as CasesIdReportRouteImport } from './routes/cases_.$id_.report'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorRoute = SupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const CctvRoute = CctvRouteImport.update({
  id: '/cctv',
  path: '/cctv',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIdRoute = CasesIdRouteImport.update({
  id: '/cases_/$id',
  path: '/cases/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIdReportRoute = CasesIdReportRouteImport.update({
  id: '/cases_/$id_/report',
  path: '/cases/$id/report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/cctv': typeof CctvRoute
  '/copilot': typeof CopilotRoute
  '/evidence': typeof EvidenceRoute
  '/graph': typeof GraphRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/supervisor': typeof SupervisorRoute
  '/timeline': typeof TimelineRoute
  '/voice': typeof VoiceRoute
  '/cases/$id': typeof CasesIdRoute
  '/cases/$id/report': typeof CasesIdReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/cctv': typeof CctvRoute
  '/copilot': typeof CopilotRoute
  '/evidence': typeof EvidenceRoute
  '/graph': typeof GraphRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/supervisor': typeof SupervisorRoute
  '/timeline': typeof TimelineRoute
  '/voice': typeof VoiceRoute
  '/cases/$id': typeof CasesIdRoute
  '/cases/$id/report': typeof CasesIdReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/cctv': typeof CctvRoute
  '/copilot': typeof CopilotRoute
  '/evidence': typeof EvidenceRoute
  '/graph': typeof GraphRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/supervisor': typeof SupervisorRoute
  '/timeline': typeof TimelineRoute
  '/voice': typeof VoiceRoute
  '/cases_/$id': typeof CasesIdRoute
  '/cases_/$id_/report': typeof CasesIdReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/cctv'
    | '/copilot'
    | '/evidence'
    | '/graph'
    | '/login'
    | '/reports'
    | '/search'
    | '/settings'
    | '/supervisor'
    | '/timeline'
    | '/voice'
    | '/cases/$id'
    | '/cases/$id/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cases'
    | '/cctv'
    | '/copilot'
    | '/evidence'
    | '/graph'
    | '/login'
    | '/reports'
    | '/search'
    | '/settings'
    | '/supervisor'
    | '/timeline'
    | '/voice'
    | '/cases/$id'
    | '/cases/$id/report'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/cctv'
    | '/copilot'
    | '/evidence'
    | '/graph'
    | '/login'
    | '/reports'
    | '/search'
    | '/settings'
    | '/supervisor'
    | '/timeline'
    | '/voice'
    | '/cases_/$id'
    | '/cases_/$id_/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRoute
  CctvRoute: typeof CctvRoute
  CopilotRoute: typeof CopilotRoute
  EvidenceRoute: typeof EvidenceRoute
  GraphRoute: typeof GraphRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SupervisorRoute: typeof SupervisorRoute
  TimelineRoute: typeof TimelineRoute
  VoiceRoute: typeof VoiceRoute
  CasesIdRoute: typeof CasesIdRoute
  CasesIdReportRoute: typeof CasesIdReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cctv': {
      id: '/cctv'
      path: '/cctv'
      fullPath: '/cctv'
      preLoaderRoute: typeof CctvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases_/$id': {
      id: '/cases_/$id'
      path: '/cases/$id'
      fullPath: '/cases/$id'
      preLoaderRoute: typeof CasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases_/$id_/report': {
      id: '/cases_/$id_/report'
      path: '/cases/$id/report'
      fullPath: '/cases/$id/report'
      preLoaderRoute: typeof CasesIdReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRoute,
  CctvRoute: CctvRoute,
  CopilotRoute: CopilotRoute,
  EvidenceRoute: EvidenceRoute,
  GraphRoute: GraphRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SupervisorRoute: SupervisorRoute,
  TimelineRoute: TimelineRoute,
  VoiceRoute: VoiceRoute,
  CasesIdRoute: CasesIdRoute,
  CasesIdReportRoute: CasesIdReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
